create table "public"."interactions_test" (
    "interactor_id" uuid not null,
    "thought_id" bigint not null,
    "created_at" timestamp with time zone not null default now()
);


alter table "public"."interactions_test" enable row level security;

create table "public"."post_interactions" (
    "interaction_id" bigint generated always as identity not null,
    "interaction_timestamp" timestamp with time zone default now(),
    "user_id" uuid not null,
    "post_id" bigint not null
);


alter table "public"."post_interactions" enable row level security;

create table "public"."post_revisions" (
    "revision_id" bigint generated always as identity not null,
    "revision_timestamp" timestamp with time zone default now(),
    "revision_type" text not null,
    "user_id" uuid not null,
    "associated_post_id" bigint not null,
    "content" text,
    "previous_content" text
);


alter table "public"."post_revisions" enable row level security;

create table "public"."posts" (
    "post_id" bigint generated always as identity not null,
    "post_timestamp" timestamp with time zone default now(),
    "user_id" uuid not null,
    "text_content" text not null,
    "like_count" integer default 0,
    "reply_count" integer default 0
);


alter table "public"."posts" enable row level security;

create table "public"."profiles" (
    "id" uuid not null,
    "created_at" timestamp with time zone not null,
    "last_edited" timestamp without time zone not null default now(),
    "username" text not null,
    "nickname" text not null,
    "bio" text
);


alter table "public"."profiles" enable row level security;

create table "public"."thoughts_test" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "user_id" uuid not null default auth.uid(),
    "text_content" text not null,
    "parent_thought" bigint
);


alter table "public"."thoughts_test" enable row level security;

CREATE INDEX idx_post_interactions_post_id ON public.post_interactions USING btree (post_id);

CREATE INDEX idx_post_interactions_timestamp ON public.post_interactions USING btree (interaction_timestamp);

CREATE INDEX idx_post_interactions_user_id ON public.post_interactions USING btree (user_id);

CREATE INDEX idx_post_revisions_post_id ON public.post_revisions USING btree (associated_post_id);

CREATE INDEX idx_post_revisions_timestamp ON public.post_revisions USING btree (revision_timestamp);

CREATE INDEX idx_post_revisions_type ON public.post_revisions USING btree (revision_type);

CREATE INDEX idx_post_revisions_user_id ON public.post_revisions USING btree (user_id);

CREATE INDEX idx_posts_like_count ON public.posts USING btree (like_count);

CREATE INDEX idx_posts_post_timestamp ON public.posts USING btree (post_timestamp);

CREATE INDEX idx_posts_user_id ON public.posts USING btree (user_id);

CREATE UNIQUE INDEX interactions_test_pkey ON public.interactions_test USING btree (interactor_id, thought_id);

CREATE UNIQUE INDEX interactor_id_thought_unique ON public.interactions_test USING btree (interactor_id, thought_id);

CREATE UNIQUE INDEX post_interactions_pkey ON public.post_interactions USING btree (interaction_id);

CREATE UNIQUE INDEX post_interactions_user_id_post_id_key ON public.post_interactions USING btree (user_id, post_id);

CREATE UNIQUE INDEX post_revisions_pkey ON public.post_revisions USING btree (revision_id);

CREATE UNIQUE INDEX posts_pkey ON public.posts USING btree (post_id);

CREATE UNIQUE INDEX profiles_pkey ON public.profiles USING btree (id);

CREATE UNIQUE INDEX profiles_username_key ON public.profiles USING btree (username);

CREATE UNIQUE INDEX thoughts_test_pkey ON public.thoughts_test USING btree (id);

alter table "public"."interactions_test" add constraint "interactions_test_pkey" PRIMARY KEY using index "interactions_test_pkey";

alter table "public"."post_interactions" add constraint "post_interactions_pkey" PRIMARY KEY using index "post_interactions_pkey";

alter table "public"."post_revisions" add constraint "post_revisions_pkey" PRIMARY KEY using index "post_revisions_pkey";

alter table "public"."posts" add constraint "posts_pkey" PRIMARY KEY using index "posts_pkey";

alter table "public"."profiles" add constraint "profiles_pkey" PRIMARY KEY using index "profiles_pkey";

alter table "public"."thoughts_test" add constraint "thoughts_test_pkey" PRIMARY KEY using index "thoughts_test_pkey";

alter table "public"."interactions_test" add constraint "interactions_test_interactor_id_fkey" FOREIGN KEY (interactor_id) REFERENCES profiles(id) not valid;

alter table "public"."interactions_test" validate constraint "interactions_test_interactor_id_fkey";

alter table "public"."interactions_test" add constraint "interactions_test_thought_id_fkey" FOREIGN KEY (thought_id) REFERENCES thoughts_test(id) not valid;

alter table "public"."interactions_test" validate constraint "interactions_test_thought_id_fkey";

alter table "public"."interactions_test" add constraint "interactor_id_thought_unique" UNIQUE using index "interactor_id_thought_unique";

alter table "public"."post_interactions" add constraint "post_interactions_post_id_fkey" FOREIGN KEY (post_id) REFERENCES posts(post_id) ON DELETE CASCADE not valid;

alter table "public"."post_interactions" validate constraint "post_interactions_post_id_fkey";

alter table "public"."post_interactions" add constraint "post_interactions_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE not valid;

alter table "public"."post_interactions" validate constraint "post_interactions_user_id_fkey";

alter table "public"."post_interactions" add constraint "post_interactions_user_id_post_id_key" UNIQUE using index "post_interactions_user_id_post_id_key";

alter table "public"."post_revisions" add constraint "post_revisions_associated_post_id_fkey" FOREIGN KEY (associated_post_id) REFERENCES posts(post_id) ON DELETE CASCADE not valid;

alter table "public"."post_revisions" validate constraint "post_revisions_associated_post_id_fkey";

alter table "public"."post_revisions" add constraint "post_revisions_revision_type_check" CHECK ((revision_type = ANY (ARRAY['edit'::text, 'deletion'::text]))) not valid;

alter table "public"."post_revisions" validate constraint "post_revisions_revision_type_check";

alter table "public"."post_revisions" add constraint "post_revisions_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE not valid;

alter table "public"."post_revisions" validate constraint "post_revisions_user_id_fkey";

alter table "public"."posts" add constraint "posts_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE not valid;

alter table "public"."posts" validate constraint "posts_user_id_fkey";

alter table "public"."profiles" add constraint "profiles_bio_check" CHECK ((length(bio) <= 128)) not valid;

alter table "public"."profiles" validate constraint "profiles_bio_check";

alter table "public"."profiles" add constraint "profiles_id_fkey" FOREIGN KEY (id) REFERENCES auth.users(id) not valid;

alter table "public"."profiles" validate constraint "profiles_id_fkey";

alter table "public"."profiles" add constraint "profiles_nickname_check" CHECK ((length(nickname) < 32)) not valid;

alter table "public"."profiles" validate constraint "profiles_nickname_check";

alter table "public"."profiles" add constraint "profiles_username_check" CHECK ((length(username) < 32)) not valid;

alter table "public"."profiles" validate constraint "profiles_username_check";

alter table "public"."profiles" add constraint "profiles_username_key" UNIQUE using index "profiles_username_key";

alter table "public"."thoughts_test" add constraint "thoughts_test_parent_thought_fkey" FOREIGN KEY (parent_thought) REFERENCES thoughts_test(id) ON DELETE RESTRICT not valid;

alter table "public"."thoughts_test" validate constraint "thoughts_test_parent_thought_fkey";

alter table "public"."thoughts_test" add constraint "thoughts_test_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) not valid;

alter table "public"."thoughts_test" validate constraint "thoughts_test_user_id_fkey";

alter table "public"."thoughts_test" add constraint "thoughts_test_user_id_fkey1" FOREIGN KEY (user_id) REFERENCES profiles(id) not valid;

alter table "public"."thoughts_test" validate constraint "thoughts_test_user_id_fkey1";

set check_function_bodies = off;

CREATE OR REPLACE FUNCTION public.get_profile(username_input text)
 RETURNS record
 LANGUAGE plpgsql
AS $function$declare
profile RECORD;
BEGIN
SELECT * INTO profile FROM public.profiles as profiles
WHERE profiles.username = username_input;
return profile;
END$function$
;

CREATE OR REPLACE FUNCTION public.get_thought_like_count(thought_id_input integer)
 RETURNS integer
 LANGUAGE plpgsql
AS $function$declare
like_count integer;
BEGIN
SELECT COUNT(*) INTO like_count
FROM public.interactions_test as interactions
WHERE interactions.thought_id = thought_id_input;
RETURN like_count;
END$function$
;

CREATE OR REPLACE FUNCTION public.get_thought_reply_count(thought_id_input integer)
 RETURNS integer
 LANGUAGE plpgsql
AS $function$declare
reply_count integer;
BEGIN
SELECT COUNT(*) INTO reply_count
FROM public.thoughts_test as thoughts
WHERE thoughts.parent_thought = thought_id_input;
RETURN reply_count;
END$function$
;

CREATE OR REPLACE FUNCTION public.get_thoughts_count(username_input text)
 RETURNS integer
 LANGUAGE plpgsql
AS $function$declare
thoughts_count int;
BEGIN
SELECT COUNT(*) INTO thoughts_count FROM public.thoughts_test as thoughts
INNER JOIN public.profiles as profiles ON profiles.id = thoughts.user_id
WHERE profiles.username = username_input;
return thoughts_count;
END$function$
;

CREATE OR REPLACE FUNCTION public.get_thoughts_for_user(username_input text)
 RETURNS SETOF record
 LANGUAGE plpgsql
AS $function$
declare
thoughts_set RECORD;
BEGIN
FOR thoughts_set IN SELECT *
FROM public.thoughts_test as thoughts
INNER JOIN public.profiles as profiles
ON profiles.id = thoughts.user_id
WHERE profiles.username = username_input
LOOP RETURN NEXT thoughts_set;
END LOOP;
RETURN;
END
$function$
;

CREATE OR REPLACE FUNCTION public.get_username_from_id(user_id_input uuid)
 RETURNS text
 LANGUAGE plpgsql
AS $function$declare
username_output text;
BEGIN
SELECT profiles.username INTO username_output FROM public.profiles as profiles
WHERE profiles.id = user_id_input;
return username_output;
END$function$
;

grant delete on table "public"."interactions_test" to "anon";

grant insert on table "public"."interactions_test" to "anon";

grant references on table "public"."interactions_test" to "anon";

grant select on table "public"."interactions_test" to "anon";

grant trigger on table "public"."interactions_test" to "anon";

grant truncate on table "public"."interactions_test" to "anon";

grant update on table "public"."interactions_test" to "anon";

grant delete on table "public"."interactions_test" to "authenticated";

grant insert on table "public"."interactions_test" to "authenticated";

grant references on table "public"."interactions_test" to "authenticated";

grant select on table "public"."interactions_test" to "authenticated";

grant trigger on table "public"."interactions_test" to "authenticated";

grant truncate on table "public"."interactions_test" to "authenticated";

grant update on table "public"."interactions_test" to "authenticated";

grant delete on table "public"."interactions_test" to "postgres";

grant insert on table "public"."interactions_test" to "postgres";

grant references on table "public"."interactions_test" to "postgres";

grant select on table "public"."interactions_test" to "postgres";

grant trigger on table "public"."interactions_test" to "postgres";

grant truncate on table "public"."interactions_test" to "postgres";

grant update on table "public"."interactions_test" to "postgres";

grant delete on table "public"."interactions_test" to "service_role";

grant insert on table "public"."interactions_test" to "service_role";

grant references on table "public"."interactions_test" to "service_role";

grant select on table "public"."interactions_test" to "service_role";

grant trigger on table "public"."interactions_test" to "service_role";

grant truncate on table "public"."interactions_test" to "service_role";

grant update on table "public"."interactions_test" to "service_role";

grant delete on table "public"."post_interactions" to "anon";

grant insert on table "public"."post_interactions" to "anon";

grant references on table "public"."post_interactions" to "anon";

grant select on table "public"."post_interactions" to "anon";

grant trigger on table "public"."post_interactions" to "anon";

grant truncate on table "public"."post_interactions" to "anon";

grant update on table "public"."post_interactions" to "anon";

grant delete on table "public"."post_interactions" to "authenticated";

grant insert on table "public"."post_interactions" to "authenticated";

grant references on table "public"."post_interactions" to "authenticated";

grant select on table "public"."post_interactions" to "authenticated";

grant trigger on table "public"."post_interactions" to "authenticated";

grant truncate on table "public"."post_interactions" to "authenticated";

grant update on table "public"."post_interactions" to "authenticated";

grant delete on table "public"."post_interactions" to "postgres";

grant insert on table "public"."post_interactions" to "postgres";

grant references on table "public"."post_interactions" to "postgres";

grant select on table "public"."post_interactions" to "postgres";

grant trigger on table "public"."post_interactions" to "postgres";

grant truncate on table "public"."post_interactions" to "postgres";

grant update on table "public"."post_interactions" to "postgres";

grant delete on table "public"."post_interactions" to "service_role";

grant insert on table "public"."post_interactions" to "service_role";

grant references on table "public"."post_interactions" to "service_role";

grant select on table "public"."post_interactions" to "service_role";

grant trigger on table "public"."post_interactions" to "service_role";

grant truncate on table "public"."post_interactions" to "service_role";

grant update on table "public"."post_interactions" to "service_role";

grant delete on table "public"."post_revisions" to "anon";

grant insert on table "public"."post_revisions" to "anon";

grant references on table "public"."post_revisions" to "anon";

grant select on table "public"."post_revisions" to "anon";

grant trigger on table "public"."post_revisions" to "anon";

grant truncate on table "public"."post_revisions" to "anon";

grant update on table "public"."post_revisions" to "anon";

grant delete on table "public"."post_revisions" to "authenticated";

grant insert on table "public"."post_revisions" to "authenticated";

grant references on table "public"."post_revisions" to "authenticated";

grant select on table "public"."post_revisions" to "authenticated";

grant trigger on table "public"."post_revisions" to "authenticated";

grant truncate on table "public"."post_revisions" to "authenticated";

grant update on table "public"."post_revisions" to "authenticated";

grant delete on table "public"."post_revisions" to "postgres";

grant insert on table "public"."post_revisions" to "postgres";

grant references on table "public"."post_revisions" to "postgres";

grant select on table "public"."post_revisions" to "postgres";

grant trigger on table "public"."post_revisions" to "postgres";

grant truncate on table "public"."post_revisions" to "postgres";

grant update on table "public"."post_revisions" to "postgres";

grant delete on table "public"."post_revisions" to "service_role";

grant insert on table "public"."post_revisions" to "service_role";

grant references on table "public"."post_revisions" to "service_role";

grant select on table "public"."post_revisions" to "service_role";

grant trigger on table "public"."post_revisions" to "service_role";

grant truncate on table "public"."post_revisions" to "service_role";

grant update on table "public"."post_revisions" to "service_role";

grant delete on table "public"."posts" to "anon";

grant insert on table "public"."posts" to "anon";

grant references on table "public"."posts" to "anon";

grant select on table "public"."posts" to "anon";

grant trigger on table "public"."posts" to "anon";

grant truncate on table "public"."posts" to "anon";

grant update on table "public"."posts" to "anon";

grant delete on table "public"."posts" to "authenticated";

grant insert on table "public"."posts" to "authenticated";

grant references on table "public"."posts" to "authenticated";

grant select on table "public"."posts" to "authenticated";

grant trigger on table "public"."posts" to "authenticated";

grant truncate on table "public"."posts" to "authenticated";

grant update on table "public"."posts" to "authenticated";

grant delete on table "public"."posts" to "postgres";

grant insert on table "public"."posts" to "postgres";

grant references on table "public"."posts" to "postgres";

grant select on table "public"."posts" to "postgres";

grant trigger on table "public"."posts" to "postgres";

grant truncate on table "public"."posts" to "postgres";

grant update on table "public"."posts" to "postgres";

grant delete on table "public"."posts" to "service_role";

grant insert on table "public"."posts" to "service_role";

grant references on table "public"."posts" to "service_role";

grant select on table "public"."posts" to "service_role";

grant trigger on table "public"."posts" to "service_role";

grant truncate on table "public"."posts" to "service_role";

grant update on table "public"."posts" to "service_role";

grant delete on table "public"."profiles" to "anon";

grant insert on table "public"."profiles" to "anon";

grant references on table "public"."profiles" to "anon";

grant select on table "public"."profiles" to "anon";

grant trigger on table "public"."profiles" to "anon";

grant truncate on table "public"."profiles" to "anon";

grant update on table "public"."profiles" to "anon";

grant delete on table "public"."profiles" to "authenticated";

grant insert on table "public"."profiles" to "authenticated";

grant references on table "public"."profiles" to "authenticated";

grant select on table "public"."profiles" to "authenticated";

grant trigger on table "public"."profiles" to "authenticated";

grant truncate on table "public"."profiles" to "authenticated";

grant update on table "public"."profiles" to "authenticated";

grant delete on table "public"."profiles" to "postgres";

grant insert on table "public"."profiles" to "postgres";

grant references on table "public"."profiles" to "postgres";

grant select on table "public"."profiles" to "postgres";

grant trigger on table "public"."profiles" to "postgres";

grant truncate on table "public"."profiles" to "postgres";

grant update on table "public"."profiles" to "postgres";

grant delete on table "public"."profiles" to "service_role";

grant insert on table "public"."profiles" to "service_role";

grant references on table "public"."profiles" to "service_role";

grant select on table "public"."profiles" to "service_role";

grant trigger on table "public"."profiles" to "service_role";

grant truncate on table "public"."profiles" to "service_role";

grant update on table "public"."profiles" to "service_role";

grant delete on table "public"."thoughts_test" to "anon";

grant insert on table "public"."thoughts_test" to "anon";

grant references on table "public"."thoughts_test" to "anon";

grant select on table "public"."thoughts_test" to "anon";

grant trigger on table "public"."thoughts_test" to "anon";

grant truncate on table "public"."thoughts_test" to "anon";

grant update on table "public"."thoughts_test" to "anon";

grant delete on table "public"."thoughts_test" to "authenticated";

grant insert on table "public"."thoughts_test" to "authenticated";

grant references on table "public"."thoughts_test" to "authenticated";

grant select on table "public"."thoughts_test" to "authenticated";

grant trigger on table "public"."thoughts_test" to "authenticated";

grant truncate on table "public"."thoughts_test" to "authenticated";

grant update on table "public"."thoughts_test" to "authenticated";

grant delete on table "public"."thoughts_test" to "postgres";

grant insert on table "public"."thoughts_test" to "postgres";

grant references on table "public"."thoughts_test" to "postgres";

grant select on table "public"."thoughts_test" to "postgres";

grant trigger on table "public"."thoughts_test" to "postgres";

grant truncate on table "public"."thoughts_test" to "postgres";

grant update on table "public"."thoughts_test" to "postgres";

grant delete on table "public"."thoughts_test" to "service_role";

grant insert on table "public"."thoughts_test" to "service_role";

grant references on table "public"."thoughts_test" to "service_role";

grant select on table "public"."thoughts_test" to "service_role";

grant trigger on table "public"."thoughts_test" to "service_role";

grant truncate on table "public"."thoughts_test" to "service_role";

grant update on table "public"."thoughts_test" to "service_role";

create policy "Enable delete for users based on user_id"
on "public"."interactions_test"
as permissive
for delete
to public
using ((( SELECT auth.uid() AS uid) = interactor_id));


create policy "Enable insert for users based on user_id"
on "public"."interactions_test"
as permissive
for insert
to public
with check ((( SELECT auth.uid() AS uid) = interactor_id));


create policy "Enable read access for all users"
on "public"."interactions_test"
as permissive
for select
to authenticated
using (true);


create policy "Enable read access for all users"
on "public"."post_interactions"
as permissive
for select
to anon
using (true);


create policy "Enable read access for all users"
on "public"."profiles"
as permissive
for select
to public
using (true);


create policy "Limit profile updates to owner"
on "public"."profiles"
as permissive
for update
to public
using (((( SELECT auth.uid() AS uid) IS NOT NULL) AND (( SELECT auth.uid() AS uid) = id)));


create policy "Enable delete for users based on user_id"
on "public"."thoughts_test"
as permissive
for delete
to authenticated
using ((( SELECT auth.uid() AS uid) = user_id));


create policy "Enable insert for users based on user_id"
on "public"."thoughts_test"
as permissive
for insert
to authenticated
with check ((( SELECT auth.uid() AS uid) = user_id));


create policy "Enable read access for authenticated users"
on "public"."thoughts_test"
as permissive
for select
to authenticated
using (true);
